name: health_coach
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.de


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.3
  google_nav_bar: ^5.0.6
  curved_navigation_bar: ^1.0.3
  flutter_native_splash: ^2.4.1
  google_fonts: ^6.2.1
  get: ^4.6.6
  flutter_otp_text_field: ^1.2.0
  smooth_page_indicator: ^1.2.0+3
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#ffffff"
  image: assets/splash_screen.png


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/
    - assets/common/
    - assets/icons/
    - assets/images/
    - assets/logo/
    - assets/svg/
    - assets/category/
    - assets/meditation/
    - assets/logo/logo.png
    - assets/logo/google_logo.png
    - assets/images/forget_password/forget-password.png
    - assets/images/forget_password/phone_ver_logo.png
    - assets/logo/google_logo.png




  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Bold.ttf
        - asset: fonts/Inter-ExtraBold.ttf
        - asset: fonts/Inter-Light.ttf
        - asset: fonts/Inter-ExtraLight.ttf
        - asset: fonts/Inter-Medium.ttf
        - asset: fonts/Inter-SemiBold.ttf
        - asset: fonts/Inter-Thin.ttf
        - asset: fonts/Inter-Black.ttf

